# Generated by Django 4.1.1 on 2022-11-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incomestatements", "0006_remove_category_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=4)),
                ("january_budget", models.FloatField(blank=True, default=0, null=True)),
                (
                    "february_budget",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("march_budget", models.FloatField(blank=True, default=0, null=True)),
                ("april_budget", models.FloatField(blank=True, default=0, null=True)),
                ("may_budget", models.FloatField(blank=True, default=0, null=True)),
                ("june_budget", models.FloatField(blank=True, default=0, null=True)),
                ("july_budget", models.FloatField(blank=True, default=0, null=True)),
                ("august_budget", models.FloatField(blank=True, default=0, null=True)),
                (
                    "september_budget",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("october_budget", models.FloatField(blank=True, default=0, null=True)),
                (
                    "november_budget",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "december_budget",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "budget_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incomestatements.category",
                    ),
                ),
            ],
        ),
    ]
