# Generated by Django 4.1.1 on 2022-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("service_area", models.CharField(blank=True, max_length=100)),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("notes", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True,
                        to="properties.property",
                        verbose_name="Properties - Hold CTRL/CMD to select multiple",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
