# Generated by Django 4.0.1 on 2022-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company_name",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="occupation",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="website_url",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_number",
            field=models.IntegerField(null=True),
        ),
    ]
