# Generated by Django 4.0.1 on 2022-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_property_loan_amount_alter_property_loan_term'),
        ('contacts', '0003_alter_contact_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='properties',
            field=models.ManyToManyField(blank=True, to='properties.Property'),
        ),
    ]
