# Generated by Django 4.0.1 on 2022-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="service_area",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
