# Generated by Django 4.1.1 on 2022-11-05 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity_class",
                    models.CharField(
                        choices=[
                            ("ES=F", "ES=F"),
                            ("YM=F", "YM=F"),
                            ("NQ=F", "NQ=F"),
                            ("RTY=F", "RTY=F"),
                            ("ZB=F", "ZB=F"),
                            ("ZN=F", "ZN=F"),
                            ("ZF=F", "ZF=F"),
                            ("ZT=F", "ZT=F"),
                            ("GC=F", "GC=F"),
                            ("MGC=F", "MGC=F"),
                            ("SI=F", "SI=F"),
                            ("SIL=F", "SIL=F"),
                            ("PL=F", "PL=F"),
                            ("HG=F", "HG=F"),
                            ("PA=F", "PA=F"),
                            ("CL=F", "CL=F"),
                            ("HO=F", "HO=F"),
                            ("NG=F", "NG=F"),
                            ("RB=F", "RB=F"),
                            ("BZ=F", "BZ=F"),
                            ("B0=F", "B0=F"),
                            ("ZC=F", "ZC=F"),
                            ("ZO=F", "ZO=F"),
                            ("KE=F", "KE=F"),
                            ("ZR=F", "ZR=F"),
                            ("ZM=F", "ZM=F"),
                            ("ZL=F", "ZL=F"),
                            ("ZS=F", "ZS=F"),
                            ("GF=F", "GF=F"),
                            ("HE=F", "HE=F"),
                            ("LE=F", "LE=F"),
                            ("CC=F", "CC=F"),
                            ("KC=F", "KC=F"),
                            ("CT=F", "CT=F"),
                            ("LBS=F", "LBS=F"),
                            ("OJ=F", "OJ=F"),
                            ("SB=F", "SB=F"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "spot_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=8
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "commodities",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity",
                    models.CharField(
                        choices=[
                            ("ES=F", "ES=F"),
                            ("YM=F", "YM=F"),
                            ("NQ=F", "NQ=F"),
                            ("RTY=F", "RTY=F"),
                            ("ZB=F", "ZB=F"),
                            ("ZN=F", "ZN=F"),
                            ("ZF=F", "ZF=F"),
                            ("ZT=F", "ZT=F"),
                            ("GC=F", "GC=F"),
                            ("MGC=F", "MGC=F"),
                            ("SI=F", "SI=F"),
                            ("SIL=F", "SIL=F"),
                            ("PL=F", "PL=F"),
                            ("HG=F", "HG=F"),
                            ("PA=F", "PA=F"),
                            ("CL=F", "CL=F"),
                            ("HO=F", "HO=F"),
                            ("NG=F", "NG=F"),
                            ("RB=F", "RB=F"),
                            ("BZ=F", "BZ=F"),
                            ("B0=F", "B0=F"),
                            ("ZC=F", "ZC=F"),
                            ("ZO=F", "ZO=F"),
                            ("KE=F", "KE=F"),
                            ("ZR=F", "ZR=F"),
                            ("ZM=F", "ZM=F"),
                            ("ZL=F", "ZL=F"),
                            ("ZS=F", "ZS=F"),
                            ("GF=F", "GF=F"),
                            ("HE=F", "HE=F"),
                            ("LE=F", "LE=F"),
                            ("CC=F", "CC=F"),
                            ("KC=F", "KC=F"),
                            ("CT=F", "CT=F"),
                            ("LBS=F", "LBS=F"),
                            ("OJ=F", "OJ=F"),
                            ("SB=F", "SB=F"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Buy", "Buy"), ("Sell", "Sell")], max_length=100
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=8
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, default=0.0, max_digits=8
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
    ]
