# Generated by Django 4.1.1 on 2022-11-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Platinum", "Platinum"),
                            ("Palladium", "Palladium"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "commodity_class",
                    models.CharField(
                        choices=[
                            ("GC=F", "GC=F"),
                            ("SI=F", "SI=F"),
                            ("PL=F", "PL=F"),
                            ("PA=F", "PA=F"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "investment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
            ],
            options={
                "verbose_name_plural": "commodities",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Buy", "Buy"), ("Sell", "Sell")], max_length=100
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=8
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, default=0.0, max_digits=8
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commodities.commodity",
                    ),
                ),
            ],
        ),
    ]
