# Generated by Django 4.1.1 on 2022-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="commodity_class",
            field=models.CharField(
                choices=[
                    ("GC=F", "GC=F"),
                    ("SI=F", "SI=F"),
                    ("PL=F", "PL=F"),
                    ("PA=F", "PA=F"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="commodity",
            field=models.CharField(
                choices=[
                    ("GC=F", "GC=F"),
                    ("SI=F", "SI=F"),
                    ("PL=F", "PL=F"),
                    ("PA=F", "PA=F"),
                ],
                max_length=50,
            ),
        ),
    ]
