# Generated by Django 4.1.1 on 2022-11-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="investment",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="weight",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
