# Generated by Django 4.1.1 on 2022-11-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0002_alter_commodity_commodity_class_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commodity",
            old_name="spot_price",
            new_name="investment",
        ),
        migrations.RemoveField(
            model_name="commodity",
            name="date",
        ),
        migrations.AddField(
            model_name="commodity",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="commodity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="commodities.commodity"
            ),
        ),
    ]
