# Generated by Django 4.1.1 on 2023-02-03 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commodities", "0003_alter_transaction_commodity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="commodity",
            unique_together={("user", "commodity_class")},
        ),
        migrations.RemoveField(
            model_name="commodity",
            name="year",
        ),
    ]
