# Generated by Django 4.1.1 on 2022-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0003_commodity_user_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="commodity_class",
            field=models.CharField(
                choices=[
                    ("GC=F", "GC=F"),
                    ("SI=F", "SI=F"),
                    ("PL=F", "PL=F"),
                    ("PA=F", "PA=F"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="name",
            field=models.CharField(
                choices=[
                    ("Gold", "Gold"),
                    ("Silver", "Silver"),
                    ("Platinum", "Platinum"),
                    ("Palladium", "Palladium"),
                ],
                max_length=50,
            ),
        ),
    ]
