# Generated by Django 4.0.1 on 2022-06-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0004_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commodity",
            name="percent",
        ),
        migrations.RemoveField(
            model_name="commodity",
            name="profit",
        ),
        migrations.RemoveField(
            model_name="commodity",
            name="total",
        ),
    ]
