# Generated by Django 4.1.1 on 2022-10-24 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "commodities",
            "0005_remove_commodity_percent_remove_commodity_profit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
