# Generated by Django 4.1.1 on 2022-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0006_commodity_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="spot_price",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="weight",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
