# Generated by Django 4.1.1 on 2022-10-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commodities",
            "0007_alter_commodity_spot_price_alter_transaction_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="spot_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=8
            ),
        ),
    ]
