# Generated by Django 4.1.1 on 2022-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0007_alter_commodity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="commodity_class",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
