# Generated by Django 4.1.1 on 2022-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commodities",
            "0008_alter_commodity_spot_price_alter_transaction_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="commodity_class",
            field=models.CharField(
                choices=[
                    ("RICE", "RICE"),
                    ("WHEAT", "WHEAT"),
                    ("SUGAR", "SUGAR"),
                    ("CORN", "CORN"),
                    ("WTIOIL", "WTIOIL"),
                    ("BRENTOIL", "BRENTOIL"),
                    ("SOYBEAN", "SOYBEAN"),
                    ("COFFEE", "COFFEE"),
                    ("XAU", "XAU"),
                    ("XAG", "XAG"),
                    ("XPD", "XPD"),
                    ("XPT", "XPT"),
                    ("XRH", "XRH"),
                    ("RUBBER", "RUBBER"),
                    ("ETHANOL", "ETHANOL"),
                    ("CPO", "CPO"),
                    ("NG", "NG"),
                    ("LUMBER", "LUMBER"),
                    ("COTTON", "COTTON"),
                    ("ROBUSTA", "ROBUSTA"),
                    ("COCOA", "COCOA"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
