# Generated by Django 4.1.1 on 2022-11-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0009_alter_commodity_commodity_class_alter_commodity_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commodity",
            options={"verbose_name_plural": "commodities"},
        ),
    ]
