# Generated by Django 4.1.1 on 2022-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0010_alter_transaction_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="commodity_class",
            field=models.CharField(
                choices=[
                    ("ROKU", "ROKU"),
                    ("GOLD", "GOLD"),
                    ("QCOM", "QCOM"),
                    ("HOOD", "HOOD"),
                    ("ETSY", "ETSY"),
                    ("SU", "SU"),
                    ("LUMN", "LUMN"),
                    ("REGN", "REGN"),
                    ("CI", "CI"),
                    ("MAR", "MAR"),
                    ("APD", "APD"),
                    ("SQQQ", "SQQQ"),
                    ("FTNT", "FTNT"),
                    ("BKNG", "BKNG"),
                    ("EBAY", "EBAY"),
                    ("MRNA", "MRNA"),
                    ("RUN", "RUN"),
                    ("GBPUSD=X", "GBPUSD=X"),
                    ("NQ=F", "NQ=F"),
                    ("COMS", "COMS"),
                    ("NFLX", "NFLX"),
                    ("HUBS", "HUBS"),
                    ("EURUSD=X", "EURUSD=X"),
                    ("ARKK", "ARKK"),
                    ("MATIC-USD", "MATIC-USD"),
                    ("DDOG", "DDOG"),
                    ("SPY", "SPY"),
                    ("NETC.CO", "NETC.CO"),
                    ("TQQQ", "TQQQ"),
                    ("BT-A.L", "BT-A.L"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
