# Generated by Django 4.1.1 on 2022-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0010_alter_commodity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="year",
            field=models.CharField(default="2022", max_length=4),
            preserve_default=False,
        ),
    ]
