# Generated by Django 4.1.1 on 2022-11-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0012_alter_commodity_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commodity",
            name="weight",
        ),
    ]
