# Generated by Django 4.1.1 on 2022-11-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0013_remove_commodity_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="weight",
            field=models.FloatField(default=0.0),
        ),
    ]
