# Generated by Django 4.1.1 on 2022-12-11 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="mark_read",
            field=models.BooleanField(default=False),
        ),
    ]
