# Generated by Django 4.1.1 on 2022-12-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0002_notification_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
    ]
