# Generated by Django 4.0.1 on 2022-05-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_delete_reminder'),
        ('reminders', '0002_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
