# Generated by Django 4.1.1 on 2022-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0003_alter_reminder_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="reminder_type",
            field=models.CharField(
                choices=[
                    ("oneoff", "One Off"),
                    ("weekly", "Weekly"),
                    ("bi-weekly", "Bi-Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("quarterly", "Quarterly"),
                ],
                default="oneoff",
                max_length=120,
            ),
        ),
    ]
