# Generated by Django 4.1.1 on 2022-12-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0005_reminder_user"),
        ("reminders", "0005_reminder_user_notification"),
    ]

    operations = []
