# Generated by Django 4.0.1 on 2022-06-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retirement_goals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retirementgoal",
            old_name="collections",
            new_name="collectables",
        ),
    ]
