# Generated by Django 4.0.1 on 2022-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('entry_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
