# Generated by Django 4.1.1 on 2023-02-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal_balances", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalbalance",
            name="date",
        ),
    ]
