# Generated by Django 4.0.1 on 2022-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("property_type", models.CharField(max_length=120)),
                ("land_size", models.DecimalField(decimal_places=2, max_digits=12)),
                ("building_size", models.IntegerField()),
                ("bedrooms", models.DecimalField(decimal_places=2, max_digits=3)),
                ("bathrooms", models.DecimalField(decimal_places=2, max_digits=3)),
                ("garage", models.DecimalField(decimal_places=2, max_digits=3)),
                ("vacancy_rate", models.DecimalField(decimal_places=2, max_digits=3)),
                ("street_address", models.TextField()),
                ("purchase_date", models.DateTimeField()),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loan_term", models.DecimalField(decimal_places=2, max_digits=3)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("repayments", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rates", models.DecimalField(decimal_places=2, max_digits=3)),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("other_income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("management_fee", models.DecimalField(decimal_places=2, max_digits=3)),
                ("insurance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("maintenance", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
