# Generated by Django 4.1.1 on 2022-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                            ("Retail", "Retail"),
                            ("Land", "Land"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "land_size",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("building_size", models.PositiveIntegerField(default=0)),
                ("lounge", models.PositiveIntegerField(default=0)),
                ("bedrooms", models.PositiveIntegerField(default=0)),
                ("bathrooms", models.PositiveIntegerField(default=0)),
                ("parking", models.PositiveIntegerField(default=0)),
                (
                    "garage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("None", "None"),
                            ("Carport", "Carport"),
                            ("Single", "Single"),
                            ("Single with Workshop", "Single with Workshop"),
                            ("Double", "Double"),
                            ("Double with Workshop", "Double with Workshop"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "vacancy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Vacancy Rate %",
                    ),
                ),
                ("street_address", models.TextField(blank=True, null=True)),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("market_value", models.PositiveIntegerField(default=1000)),
                ("purchase_price", models.PositiveIntegerField(default=0)),
                ("deposit", models.PositiveIntegerField(default=0)),
                ("loan_amount", models.PositiveIntegerField(default=0)),
                ("loan_term", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Interest Rate %"
                    ),
                ),
                ("repayments", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rates", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rent", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "other_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=12
                    ),
                ),
                (
                    "bodycorp_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=6
                    ),
                ),
                (
                    "management_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Management fee %",
                    ),
                ),
                (
                    "insurance",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=12
                    ),
                ),
                (
                    "maintenance",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=12
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="no_picture.png", upload_to="products"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        max_length=120,
                    ),
                ),
                ("comments", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Capital Introduced", "Capital Introduced"),
                            ("Management Fee", "Management Fee"),
                            ("Insurance", "Insurance"),
                            ("Interest", "Interest"),
                            ("Mortage", "Mortage"),
                            ("Repairs and Maintenance", "Repairs and Maintenance"),
                            ("Rates", "Rates"),
                            ("Rent Received", "Rent Received"),
                            ("Sundry Expense", "Sundry Expense"),
                            ("Other", "Other"),
                        ],
                        max_length=128,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "property_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
