# Generated by Django 4.0.1 on 2022-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_property_garage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="insurance",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="property",
            name="loan_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="loan_term",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="property",
            name="maintenance",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="management_fee",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="property",
            name="market_value",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="other_income",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="rates",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="property",
            name="rent",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="vacancy_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
