# Generated by Django 4.0.1 on 2022-01-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_insurance_alter_property_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
