# Generated by Django 4.0.1 on 2022-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_other_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rates',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
