# Generated by Django 4.0.1 on 2022-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Capital Introduced', 'Capital Introduced'), ('Management Fee', 'Management Fee'), ('Insurance', 'Insurance'), ('Interest', 'Interest'), ('Mortage', 'Mortage'), ('Repairs and Maintenance', 'Repairs and Maintenance'), ('Rates', 'Rates'), ('Rent Received', 'Rent Received'), ('Sundry Expense', 'Sundry Expense'), ('Other', 'Other')], max_length=128),
        ),
    ]
