# Generated by Django 4.0.1 on 2022-01-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_alter_transactions_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactions",
            options={"verbose_name_plural": "Transactions"},
        ),
    ]
