# Generated by Django 4.0.1 on 2022-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='comments',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
