# Generated by Django 4.0.1 on 2022-01-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_transactions_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
