# Generated by Django 4.0.1 on 2022-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0017_alter_property_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="insurance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="maintenance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="management_fee",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=6, null=True
            ),
        ),
    ]
