# Generated by Django 4.0.1 on 2022-01-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_property_insurance_alter_property_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='insurance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='property',
            name='other_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
