# Generated by Django 4.0.1 on 2022-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_insurance_alter_property_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='loan_to_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
    ]
