# Generated by Django 4.0.1 on 2022-04-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_loan_to_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='loan_to_value',
        ),
    ]
