# Generated by Django 4.0.1 on 2022-04-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_reminders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminders',
            new_name='Reminder',
        ),
    ]
