# Generated by Django 4.0.1 on 2022-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_rename_reminders_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurring',
            field=models.BooleanField(null=True),
        ),
    ]
