# Generated by Django 4.0.1 on 2022-04-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0025_remove_reminder_recurring_reminder_reminder_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reminder",
        ),
    ]
