# Generated by Django 4.0.1 on 2022-05-08 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0026_delete_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="purchase_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
