# Generated by Django 4.0.1 on 2022-05-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Land Size (sqm)'),
        ),
    ]
