# Generated by Django 4.0.1 on 2022-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0035_property_bodycorp_fee_alter_property_management_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="market_value",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
