# Generated by Django 4.0.1 on 2022-05-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0036_alter_property_market_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="loan_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="property",
            name="loan_term",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
