# Generated by Django 4.1.1 on 2022-12-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockticker",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="stockticker",
            name="ticker",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
