# Generated by Django 4.1.1 on 2022-11-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_portfolios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocktransaction",
            old_name="coin",
            new_name="stock",
        ),
    ]
