# Generated by Django 4.1.1 on 2022-12-09 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock_portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="spot_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name="stockticker",
            unique_together={("ticker", "user")},
        ),
    ]
