# Generated by Django 4.1.1 on 2022-11-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_portfolios", "0002_rename_coin_stocktransaction_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="investment",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="spot_price",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
