# Generated by Django 4.1.1 on 2022-12-09 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock_portfolios", "0002_alter_stockticker_name_alter_stockticker_ticker"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockticker",
            unique_together={("name", "ticker", "user")},
        ),
    ]
