# Generated by Django 4.1.1 on 2023-02-06 06:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock_portfolios", "0002_alter_stocktransaction_spot_price_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("user", "stock_ticker")},
        ),
        migrations.RemoveField(
            model_name="stock",
            name="year",
        ),
    ]
