# Generated by Django 4.1.1 on 2022-12-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock_portfolios", "0003_alter_stockticker_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="stock",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_ticker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock_portfolios.stockticker",
            ),
            preserve_default=False,
        ),
    ]
