# Generated by Django 4.1.1 on 2022-11-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_portfolios", "0006_alter_stock_unique_together_stock_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="quantity",
        ),
    ]
