# Generated by Django 4.1.1 on 2022-11-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_portfolios", "0007_remove_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
    ]
