# Generated by Django 4.1.1 on 2023-01-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Contact Us"},
        ),
    ]
