# Generated by Django 4.1.1 on 2022-10-13 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flows", "0002_cashflow_frequency_alter_cashflow_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflow",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
