# Generated by Django 4.0.1 on 2022-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('transaction_type', models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
