# Generated by Django 4.0.1 on 2022-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomestatements', '0002_category_remove_incomestatement_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
