# Generated by Django 4.1.1 on 2023-01-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("incomestatements", "0004_alter_category_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incomestatements.categoryname",
            ),
        ),
    ]
