# Generated by Django 4.1.1 on 2022-11-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomestatements", "0005_category_budget_category_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="budget",
        ),
    ]
