# Generated by Django 4.1.1 on 2023-01-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("incomestatements", "0006_categoryname_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomestatement",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incomestatements.categoryname",
            ),
        ),
    ]
