# Generated by Django 4.1.1 on 2022-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomestatements", "0006_remove_category_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="yearly_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12
            ),
        ),
    ]
