# Generated by Django 4.1.1 on 2022-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomestatements", "0007_category_yearly_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="april_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="august_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="december_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="february_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="january_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="july_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="june_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="march_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="may_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="november_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="october_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="september_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
