# Generated by Django 4.0.1 on 2022-08-23 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0037_alter_property_loan_amount_alter_property_loan_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('transaction_type', models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyIncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('propcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incomestatements_property.propertycategory')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
    ]
