# Generated by Django 4.1.1 on 2023-01-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomestatements_property", "0002_alter_propertycategory_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="propertycategory",
            unique_together={("name", "year", "transaction_type")},
        ),
    ]
