# Generated by Django 4.1.1 on 2022-12-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incomestatements_property",
            "0002_propertycategory_user_propertyincomestatement_user",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertycategory",
            name="april_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="august_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="december_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="february_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="january_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="july_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="june_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="march_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="may_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="november_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="october_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="september_budget",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="propertycategory",
            name="year",
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
