# Generated by Django 4.0.1 on 2022-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("ticker", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=4, default=0.0, max_digits=12
                    ),
                ),
                (
                    "spot_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=12
                    ),
                ),
            ],
        ),
    ]
