# Generated by Django 4.1.1 on 2022-10-13 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
