# Generated by Django 4.1.1 on 2022-11-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="investment",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cryptotransaction",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cryptotransaction",
            name="spot_price",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
