# Generated by Django 4.1.1 on 2023-02-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="crypto",
            unique_together=set(),
        ),
    ]
