# Generated by Django 4.1.1 on 2023-02-06 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crypto", "0002_alter_crypto_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="crypto",
            unique_together={("user", "crypto_ticker")},
        ),
        migrations.RemoveField(
            model_name="crypto",
            name="year",
        ),
    ]
