# Generated by Django 4.1.1 on 2022-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0002_alter_crypto_investment_alter_crypto_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrudUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
