# Generated by Django 4.1.1 on 2022-11-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0006_alter_crypto_name_alter_crypto_ticker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crypto",
            name="quantity",
        ),
    ]
