# Generated by Django 4.1.1 on 2022-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0008_crypto_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="crypto",
            name="year",
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
