# Generated by Django 4.0.1 on 2022-05-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeTradedFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("ticker", models.CharField(max_length=6)),
                ("asset_class", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="IndexFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("ticker", models.CharField(max_length=6)),
                ("asset_class", models.CharField(max_length=30)),
            ],
        ),
    ]
