# Generated by Django 4.0.1 on 2022-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradedfund',
            name='ticker',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='indexfund',
            name='ticker',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
