# Generated by Django 4.0.1 on 2022-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market_funds", "0003_trade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trade",
        ),
    ]
