# Generated by Django 4.0.1 on 2022-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_funds', '0004_delete_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('share_price_at_purchase', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('asset_class', models.CharField(blank=True, choices=[('Equities', 'Equities'), ('Bonds', 'Bonds'), ('Cash & Cash Equivalents', 'Cash & Cash Equivalents'), ('Commodites', 'Commodites'), ('Diversified', 'Diversified'), ('Reits', 'Reits'), ('Other', 'Other')], max_length=100, null=True)),
            ],
        ),
    ]
