# Generated by Django 4.0.1 on 2022-05-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_funds", "0005_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="indexfund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="market_funds.indexfund",
            ),
        ),
    ]
