# Generated by Django 4.0.1 on 2022-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_funds', '0007_trade_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='share_price_at_purchase',
            new_name='current_share_price',
        ),
    ]
