# Generated by Django 4.0.1 on 2022-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_funds', '0011_delete_exchangetradedfund_indexfund_fund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexfund',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='indexfund',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
