# Generated by Django 4.1.1 on 2022-10-13 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "market_funds",
            "0014_alter_indexfund_shares_alter_trade_share_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="indexfund",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
