# Generated by Django 4.1.1 on 2022-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_funds", "0015_indexfund_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexfund",
            name="share_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0.0, max_digits=12
            ),
        ),
    ]
